#pragma once

#include "index.h"

namespace shadder {
    using ::Callable;
    using ::CallableCustom;
    using ::CallableCustomFunction;
    using ::CameraComponent;
    using ::CameraSystem;
    using ::ColliderComponent;
    using ::CollisionSystem;
    using ::ComponentBase;
    using ::ComponentTypeID;
    using ::DirectionalLightComponent;
    using ::Display;
    using ::DisplayWin32;
    using ::Entity;
    using ::EntityGeneration;
    using ::EntityIndex;
    using ::Game;
    using ::IComponentStorage;
    using ::INVALID_COMPONENT_TYPE;
    using ::INVALID_ENTITY_INDEX;
    using ::INVALID_GENERATION;
    using ::ISystem;
    using ::ImGuiContext;
    using ::ImGuiIO;
    using ::ImGuiViewport;
    using ::InputDevice;
    using ::InstanceTag;
    using ::InstancedMeshComponent;
    using ::InstancedRenderSystem;
    using ::Keys;
    using ::MaterialComponent;
    using ::MeshComponent;
    using ::MovementSystem;
    using ::ObjLoader;
    using ::ObjMeshData;
    using ::PhongMaterialComponent;
    using ::PhongMaterialDesc;
    using ::Query;
    using ::RenderSystem;
    using ::ResourceLoader;
    using ::ScreenSize;
    using ::Signal;
    using ::SparseSetStorage;
    using ::SystemPhase;
    using ::Texture2D;
    using ::TextureLoader;
    using ::Transform3D;
    using ::VelocityComponent;
    using ::Vertex3D;
    using ::World;
}
